# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: scalica.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='scalica.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\rscalica.proto\"\x1b\n\tUsersInfo\x12\x0e\n\x06userId\x18\x01 \x01(\x05\"/\n\x14UsersRecommendations\x12\x17\n\x0frecommendations\x18\x01 \x03(\t\".\n\nRemoveInfo\x12\x0e\n\x06userId\x18\x01 \x01(\x05\x12\x10\n\x08removeId\x18\x02 \x01(\x05\"\t\n\x07Nothing2y\n\x0bRecommender\x12\x39\n\x12GetRecommendations\x12\n.UsersInfo\x1a\x15.UsersRecommendations\"\x00\x12/\n\x14RemoveRecommendation\x12\x0b.RemoveInfo\x1a\x08.Nothing\"\x00\x62\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_USERSINFO = _descriptor.Descriptor(
  name='UsersInfo',
  full_name='UsersInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='userId', full_name='UsersInfo.userId', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=17,
  serialized_end=44,
)


_USERSRECOMMENDATIONS = _descriptor.Descriptor(
  name='UsersRecommendations',
  full_name='UsersRecommendations',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='recommendations', full_name='UsersRecommendations.recommendations', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=46,
  serialized_end=93,
)


_REMOVEINFO = _descriptor.Descriptor(
  name='RemoveInfo',
  full_name='RemoveInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='userId', full_name='RemoveInfo.userId', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='removeId', full_name='RemoveInfo.removeId', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=95,
  serialized_end=141,
)


_NOTHING = _descriptor.Descriptor(
  name='Nothing',
  full_name='Nothing',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=143,
  serialized_end=152,
)

DESCRIPTOR.message_types_by_name['UsersInfo'] = _USERSINFO
DESCRIPTOR.message_types_by_name['UsersRecommendations'] = _USERSRECOMMENDATIONS
DESCRIPTOR.message_types_by_name['RemoveInfo'] = _REMOVEINFO
DESCRIPTOR.message_types_by_name['Nothing'] = _NOTHING

UsersInfo = _reflection.GeneratedProtocolMessageType('UsersInfo', (_message.Message,), dict(
  DESCRIPTOR = _USERSINFO,
  __module__ = 'scalica_pb2'
  # @@protoc_insertion_point(class_scope:UsersInfo)
  ))
_sym_db.RegisterMessage(UsersInfo)

UsersRecommendations = _reflection.GeneratedProtocolMessageType('UsersRecommendations', (_message.Message,), dict(
  DESCRIPTOR = _USERSRECOMMENDATIONS,
  __module__ = 'scalica_pb2'
  # @@protoc_insertion_point(class_scope:UsersRecommendations)
  ))
_sym_db.RegisterMessage(UsersRecommendations)

RemoveInfo = _reflection.GeneratedProtocolMessageType('RemoveInfo', (_message.Message,), dict(
  DESCRIPTOR = _REMOVEINFO,
  __module__ = 'scalica_pb2'
  # @@protoc_insertion_point(class_scope:RemoveInfo)
  ))
_sym_db.RegisterMessage(RemoveInfo)

Nothing = _reflection.GeneratedProtocolMessageType('Nothing', (_message.Message,), dict(
  DESCRIPTOR = _NOTHING,
  __module__ = 'scalica_pb2'
  # @@protoc_insertion_point(class_scope:Nothing)
  ))
_sym_db.RegisterMessage(Nothing)


import grpc
from grpc.beta import implementations as beta_implementations
from grpc.beta import interfaces as beta_interfaces
from grpc.framework.common import cardinality
from grpc.framework.interfaces.face import utilities as face_utilities


class RecommenderStub(object):
  """Recommender service rpc
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetRecommendations = channel.unary_unary(
        '/Recommender/GetRecommendations',
        request_serializer=UsersInfo.SerializeToString,
        response_deserializer=UsersRecommendations.FromString,
        )
    self.RemoveRecommendation = channel.unary_unary(
        '/Recommender/RemoveRecommendation',
        request_serializer=RemoveInfo.SerializeToString,
        response_deserializer=Nothing.FromString,
        )


class RecommenderServicer(object):
  """Recommender service rpc
  """

  def GetRecommendations(self, request, context):
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def RemoveRecommendation(self, request, context):
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_RecommenderServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetRecommendations': grpc.unary_unary_rpc_method_handler(
          servicer.GetRecommendations,
          request_deserializer=UsersInfo.FromString,
          response_serializer=UsersRecommendations.SerializeToString,
      ),
      'RemoveRecommendation': grpc.unary_unary_rpc_method_handler(
          servicer.RemoveRecommendation,
          request_deserializer=RemoveInfo.FromString,
          response_serializer=Nothing.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'Recommender', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))


class BetaRecommenderServicer(object):
  """The Beta API is deprecated for 0.15.0 and later.

  It is recommended to use the GA API (classes and functions in this
  file not marked beta) for all further purposes. This class was generated
  only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0."""
  """Recommender service rpc
  """
  def GetRecommendations(self, request, context):
    context.code(beta_interfaces.StatusCode.UNIMPLEMENTED)
  def RemoveRecommendation(self, request, context):
    context.code(beta_interfaces.StatusCode.UNIMPLEMENTED)


class BetaRecommenderStub(object):
  """The Beta API is deprecated for 0.15.0 and later.

  It is recommended to use the GA API (classes and functions in this
  file not marked beta) for all further purposes. This class was generated
  only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0."""
  """Recommender service rpc
  """
  def GetRecommendations(self, request, timeout, metadata=None, with_call=False, protocol_options=None):
    raise NotImplementedError()
  GetRecommendations.future = None
  def RemoveRecommendation(self, request, timeout, metadata=None, with_call=False, protocol_options=None):
    raise NotImplementedError()
  RemoveRecommendation.future = None


def beta_create_Recommender_server(servicer, pool=None, pool_size=None, default_timeout=None, maximum_timeout=None):
  """The Beta API is deprecated for 0.15.0 and later.

  It is recommended to use the GA API (classes and functions in this
  file not marked beta) for all further purposes. This function was
  generated only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0"""
  request_deserializers = {
    ('Recommender', 'GetRecommendations'): UsersInfo.FromString,
    ('Recommender', 'RemoveRecommendation'): RemoveInfo.FromString,
  }
  response_serializers = {
    ('Recommender', 'GetRecommendations'): UsersRecommendations.SerializeToString,
    ('Recommender', 'RemoveRecommendation'): Nothing.SerializeToString,
  }
  method_implementations = {
    ('Recommender', 'GetRecommendations'): face_utilities.unary_unary_inline(servicer.GetRecommendations),
    ('Recommender', 'RemoveRecommendation'): face_utilities.unary_unary_inline(servicer.RemoveRecommendation),
  }
  server_options = beta_implementations.server_options(request_deserializers=request_deserializers, response_serializers=response_serializers, thread_pool=pool, thread_pool_size=pool_size, default_timeout=default_timeout, maximum_timeout=maximum_timeout)
  return beta_implementations.server(method_implementations, options=server_options)


def beta_create_Recommender_stub(channel, host=None, metadata_transformer=None, pool=None, pool_size=None):
  """The Beta API is deprecated for 0.15.0 and later.

  It is recommended to use the GA API (classes and functions in this
  file not marked beta) for all further purposes. This function was
  generated only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0"""
  request_serializers = {
    ('Recommender', 'GetRecommendations'): UsersInfo.SerializeToString,
    ('Recommender', 'RemoveRecommendation'): RemoveInfo.SerializeToString,
  }
  response_deserializers = {
    ('Recommender', 'GetRecommendations'): UsersRecommendations.FromString,
    ('Recommender', 'RemoveRecommendation'): Nothing.FromString,
  }
  cardinalities = {
    'GetRecommendations': cardinality.Cardinality.UNARY_UNARY,
    'RemoveRecommendation': cardinality.Cardinality.UNARY_UNARY,
  }
  stub_options = beta_implementations.stub_options(host=host, metadata_transformer=metadata_transformer, request_serializers=request_serializers, response_deserializers=response_deserializers, thread_pool=pool, thread_pool_size=pool_size)
  return beta_implementations.dynamic_stub(channel, 'Recommender', cardinalities, options=stub_options)
# @@protoc_insertion_point(module_scope)
